In [1]:
#Exercise 1: Create a 2×5 NumPy array

import numpy as np

# Create an array from 1 to 10
arr = np.arange(1, 11)

# Reshape it into a 2x5 matrix
matrix = arr.reshape(2, 5)

print(matrix)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [3]:
#Exercise 2: Extract elements from index 5 to 15

# Create an array from 1 to 20
arr = np.arange(1, 21)

# Extract elements from index 5 to 15
extracted_elements = arr[5:16]

print(extracted_elements)


[ 6  7  8  9 10 11 12 13 14 15 16]


In [7]:
#Exercise 3: Create a Pandas Series and add a new item

import pandas as pd

# Create the initial series
fruits = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})

# Adding a new item
fruits['pears'] = 4

print(fruits)


apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [9]:
#Exercise 4: Create a DataFrame with name, age, and gender.

# Define data
data = {
    'name': ['John', 'Emma', 'Liam', 'Olivia', 'Noah', 'Ava', 'Sophia', 'Mason', 'Isabella', 'James'],
    'age': [28, 34, 21, 29, 42, 37, 31, 26, 33, 30],
    'gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Female', 'Male', 'Female', 'Male']
}

# Create DataFrame
df = pd.DataFrame(data)

print(df)


       name  age  gender
0      John   28    Male
1      Emma   34  Female
2      Liam   21    Male
3    Olivia   29  Female
4      Noah   42    Male
5       Ava   37  Female
6    Sophia   31  Female
7     Mason   26    Male
8  Isabella   33  Female
9     James   30    Male


In [11]:
#Exercise 5: Add an occupation column.

# Add occupation column with predefined values
df['occupation'] = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 
                    'Programmer', 'Manager', 'Analyst', 'Programmer']

print(df)


       name  age  gender  occupation
0      John   28    Male  Programmer
1      Emma   34  Female     Manager
2      Liam   21    Male     Analyst
3    Olivia   29  Female  Programmer
4      Noah   42    Male     Manager
5       Ava   37  Female     Analyst
6    Sophia   31  Female  Programmer
7     Mason   26    Male     Manager
8  Isabella   33  Female     Analyst
9     James   30    Male  Programmer


In [13]:
#Exercise 6: Select rows where age ≥ 30

# Filter rows where age is 30 or more
filtered_df = df[df['age'] >= 30]

print(filtered_df)


       name  age  gender  occupation
1      Emma   34  Female     Manager
4      Noah   42    Male     Manager
5       Ava   37  Female     Analyst
6    Sophia   31  Female  Programmer
8  Isabella   33  Female     Analyst
9     James   30    Male  Programmer


In [23]:
#Exercise 7: Convert DataFrame to CSV and read it back.

# Save to CSV
df.to_csv('data.csv', index=False)

# Read CSV file
df_read = pd.read_csv('data.csv')

# Display contents
print(df_read)



       name  age  gender  occupation
0      John   28    Male  Programmer
1      Emma   34  Female     Manager
2      Liam   21    Male     Analyst
3    Olivia   29  Female  Programmer
4      Noah   42    Male     Manager
5       Ava   37  Female     Analyst
6    Sophia   31  Female  Programmer
7     Mason   26    Male     Manager
8  Isabella   33  Female     Analyst
9     James   30    Male  Programmer
